path:
    root: /home/vmar0011/scratch/05_Metabolic_Networks/Test_dataset/3_Models/5_MICOM
folder:
    logs: z_snakemake_logs
    tables_fp: 0_MAGs_tables
    pickles: 1_communities
    exchanges: 2_exchanges
cores:
    build_comm: 1
    exchanges: 2
partition:
    build_comm: short,comp
    exchanges: short,comp
media_db:
    metagem_media: 0_diet/western_diet_gut_carveme.qza
